### ISSUE TITLE
Weird texture issue

### ISSUE THREAD

**Issue by Sediments** [Sediments/Compressions#1]
Some other mod seems to be causing the automatically generated assets (translations, textures, models) to fail to save properly.

[`List of suspect mods`](http://i.imgur.com/qllyBmV.png)

EDIT: Actually it doesn't seem to be another mod, it's probably a difference between my development environment and real life.

**Comment by MadRatSRP** [comment]
java.nio.file.ClosedFileSystemException
	at com.sun.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1084)
	at com.sun.nio.zipfs.ZipFileSystem.getFileAttributes(ZipFileSystem.java:316)
	at com.sun.nio.zipfs.ZipPath.checkAccess(ZipPath.java:767)
	at com.sun.nio.zipfs.ZipFileSystemProvider.checkAccess(ZipFileSystemProvider.java:187)
	at java.nio.file.Files.exists(Unknown Source)
	at com.saftno.compressions.Textures$Generation.getFileData(Textures.java:129)
	at com.saftno.compressions.Textures$Generation.Blocks(Textures.java:926)
	at com.saftno.compressions.Textures.Register(Textures.java:98)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_222_Textures_Register_DrawScreenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:549)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1433)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.sun.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1084)
	at com.sun.nio.zipfs.ZipFileSystem.getFileAttributes(ZipFileSystem.java:316)
	at com.sun.nio.zipfs.ZipPath.checkAccess(ZipPath.java:767)
	at com.sun.nio.zipfs.ZipFileSystemProvider.checkAccess(ZipFileSystemProvider.java:187)
	at java.nio.file.Files.exists(Unknown Source)
	at com.saftno.compressions.Textures$Generation.getFileData(Textures.java:129)
	at com.saftno.compressions.Textures$Generation.Blocks(Textures.java:926)
	at com.saftno.compressions.Textures.Register(Textures.java:98)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_222_Textures_Register_DrawScreenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:549)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
	Mouse location: Scaled: (0, 255). Absolute: (0, 0)
	Screen size: Scaled: (342, 256). Absolute: (1024, 768). Scale factor of 3
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1433)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**1.1.0**

**Comment by Sediments** [comment]
Try this (rename the file back to jar thou as I can't upload jar files directly here)
[Compressions-1.12.1-1.1.1.zip](https://github.com/Sediments/Compressions/files/1208175/Compressions-1.12.1-1.1.1.zip)

**Comment by MadRatSRP** [comment]
java.nio.file.ClosedFileSystemException
	at com.sun.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1084)
	at com.sun.nio.zipfs.ZipFileSystem.getFileAttributes(ZipFileSystem.java:316)
	at com.sun.nio.zipfs.ZipPath.checkAccess(ZipPath.java:767)
	at com.sun.nio.zipfs.ZipFileSystemProvider.checkAccess(ZipFileSystemProvider.java:187)
	at java.nio.file.Files.exists(Unknown Source)
	at com.saftno.compressions.Languages.Generate(Languages.java:104)
	at com.saftno.compressions.Languages.Register(Languages.java:84)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_221_Languages_Register_DrawScreenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:549)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1433)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.sun.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1084)
	at com.sun.nio.zipfs.ZipFileSystem.getFileAttributes(ZipFileSystem.java:316)
	at com.sun.nio.zipfs.ZipPath.checkAccess(ZipPath.java:767)
	at com.sun.nio.zipfs.ZipFileSystemProvider.checkAccess(ZipFileSystemProvider.java:187)
	at java.nio.file.Files.exists(Unknown Source)
	at com.saftno.compressions.Languages.Generate(Languages.java:104)
	at com.saftno.compressions.Languages.Register(Languages.java:84)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_221_Languages_Register_DrawScreenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:549)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
	Mouse location: Scaled: (0, 255). Absolute: (0, 0)
	Screen size: Scaled: (342, 256). Absolute: (1024, 768). Scale factor of 3
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1433)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Thats what i got using the latest version and yes, i renamed to jar

**Comment by MadRatSRP** [comment]
Models - Blockstates: start
Models - Blockstates - block: tile.minecraft_cobblestone_1x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_cobblestone_2x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_dirt_0_1x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_dirt_0_2x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_dirt_1_1x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_dirt_1_2x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_dirt_2_1x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_dirt_2_2x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_sand_0_1x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_sand_0_2x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_sand_1_1x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Models - Blockstates - block: tile.minecraft_sand_1_2x
Models - Blockstates - loc: start
Models - Blockstates - loc: end
Models - Blockstates - json: start
Models - Blockstates - json: end
Models - Blockstates - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Models - Blockstates - mod: start
Models - Blockstates - mod: end
Models - Blockstates - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Models - Blockstates - tmp: start
Models - Blockstates - tmp: end
Textures - Blocks: start
Textures - Blocks - frame: start
Textures - Blocks - frame: end
Textures - Blocks - side: start
Textures - Blocks - side: end
Textures - Blocks - block: tile.minecraft_cobblestone_1x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_cobblestone_2x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_dirt_0_1x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_dirt_0_2x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_dirt_1_1x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_dirt_1_2x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_dirt_2_1x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_dirt_2_2x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_sand_0_1x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_sand_0_2x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_sand_1_1x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
Textures - Blocks - block: tile.minecraft_sand_1_2x
Textures - Blocks - get2DTexData: start
Textures - Blocks - get2DTexData: end
Textures - Blocks - averagePixel: start
Textures - Blocks - averagePixel: end
Textures - Blocks - colorPixels: start
Textures - Blocks - colorPixels: end
Textures - Blocks - transparent: start
Textures - Blocks - transparent: end
Textures - Blocks - joinPixels: start
Textures - Blocks - joinPixels: end
Textures - Blocks - darkenPixels: start
Textures - Blocks - darkenPixels: end
Textures - Blocks - mod: C:\Minecraft\Instances\Hmmm\mods\Compressions-.1.12.1.-.1.1.2.jar
Textures - Blocks - mod: start
Textures - Blocks - mod: end
Textures - Blocks - tmp: C:\Minecraft\Instances\Hmmm\resourcepacks\Compressions.zip
Textures - Blocks - tmp: start
Textures - Blocks - tmp: end
 and here is the log file

**Comment by Sediments** [comment]
No need for the log any more, I pretty much know where the problem is now. 

Try this 
[Compressions-[1.12.1]-[1.1.3].zip](https://github.com/Sediments/Compressions/files/1208876/Compressions-.1.12.1.-.1.1.3.zip)

**Comment by MadRatSRP** [comment]
so the good news is: its finally working . The bad news is : textures are magenta =(

**Comment by Sediments** [comment]
Haha, damn, does the jar file have an "assets" folder?

**Comment by MadRatSRP** [comment]
nope...

**Comment by Sediments** [comment]
Ghaaa, try this, post the log.
[Compressions-[1.12.1]-[1.1.4].zip](https://github.com/Sediments/Compressions/files/1209591/Compressions-.1.12.1.-.1.1.4.zip)

**Comment by MadRatSRP** [comment]
I checked and textures are not working. I deleted config and resourcepack, but it didnt help at all. in jar i have 3 folders:utility,Meta-Inf and com, assets are not generating

**Comment by Sediments** [comment]
Did the log generate?

The problem is, for some reason, I'm not getting asses to the jar file. I could be wrong in entering it's location, or it could be locked.  

Anyway, I've now completely remove writing the the jar file, just the resource file, it should now work?
[Compressions-[1.12.1]-[1.1.5].zip](https://github.com/Sediments/Compressions/files/1211277/Compressions-.1.12.1.-.1.1.5.zip)

**Comment by MadRatSRP** [comment]
yes, here what it contained: file:/C:/Minecraft/Instances/Hmmm/mods/Compressions-.1.12.1.-.1.1.4.jar!/com/saftno/compressions/_0_Base.class

**Comment by Sediments** [comment]
Does 1.1.5 work?

**Comment by MadRatSRP** [comment]
Its working!!!! 0_0

**Comment by Sediments** [comment]
OH THANK GOD!!! Finally! This problem really had me by balls, if this didn't work I don't know what I would've done. Anyway, that you A LOT, you really helped me.

**Comment by MadRatSRP** [comment]
Thanks you as well) I have an idea, but i dont know could it be real or not. U made textures for compressed blocks, so what about compressed things from mods, that has the same texture as non-compressed block? They would all look the same, yes, but at least they would have different names

**Comment by MadRatSRP** [comment]
One more idea is to add rules of compacting, that act different than 9x. For example, items that crafts in blocks like clay. If i put them in compacting drawer, it doesnt stack to block, but clay balls stack in clay block.
So, if there is x9-x81 as a normal, there should be x4-x36, but with ability to write it for each item, for example, 
actuallyadditions:item_misc-x4-x36 or something like that.
Just an idea, but maybe u'll find it interesting)

**Comment by Sediments** [comment]
Hmm, I'm not really getting the first item, they look exactly the same, just with different names?

The second one is something I'm definitely going to do. Just like how you can now control the level of compression, you're gonna have a variable in the config file to control the size of compression. It's gonna be between 2 and 9. And eventually I'll add support for per item setting, like for example, you can have sand be 2x and 4 grid, and cobblestone be 4x and 9 grid. Hmm, maybe I'll name it like 3x4 (for the 3 levels of compression of 4 per pack), 4x9 (4 level, 9 grid). 

And, I think you can open issues and label them as enhancements if you have suggestions for improvement. Open both of these and I'll implement them. 

Thou with this error I've had to almost completely change the way my mod works, so I'll be cleaning up for days. So I'll get to the suggestions after that.
