### ISSUE TITLE
Strange Issue (2.0.5)

### ISSUE THREAD

**Issue by MadRatSRP** [Sediments/Compressions#14]
![issue](https://user-images.githubusercontent.com/29717217/29625910-c7bda178-8835-11e7-8e36-cd774b2b7aa2.png)
**Modlist without compressions**
java.lang.NullPointerException: Initializing game
	at com.saftno.compressions.ResourcePacks.Path(ResourcePacks.java:136)
	at com.saftno.compressions.Languages.Generate(Languages.java:52)
	at com.saftno.compressions.Languages.Register(Languages.java:38)
	at com.saftno.compressions.Base.Register(Base.java:60)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_126_Base_Register_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:738)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:779)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:343)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Sediments** [comment]
This is another error related to resource packs.

I'm currently rewriting the mod to not use them any more so wait for that. Should be in a couple of days.

**Comment by Sediments** [comment]
Should be fine now.

[3.0.0](https://github.com/Sediments/Compressions/releases/tag/v3.0.0)
